version: 2

elixir_version: &elixir_version
  ELIXIR_VERSION: 1.9.4-otp-22

defaults: &defaults
  working_directory: /nerves/build
  docker:
    - image: nervesproject/nerves_system_br:1.10.0

install_elixir: &install_elixir
  run:
    name: Install Elixir
    command: |
      wget https://repo.hex.pm/builds/elixir/v${ELIXIR_VERSION}.zip
      unzip -d /usr/local/elixir v${ELIXIR_VERSION}.zip
      echo 'export PATH=/usr/local/elixir/bin:$PATH' >> $BASH_ENV

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      cd /tmp
      mix local.hex --force
      mix local.rebar --force

install_nerves_bootstrap: &install_nerves_bootstrap
  run:
    name: Install nerves_bootstrap
    command: |
      cd /tmp
      mix archive.install hex nerves_bootstrap "~> 1.0" --force

fake_ssh_keys: &fake_ssh_keys
  run:
    name: Generage bogus keys
    command: |
      rm -f ~/.ssh/id_rsa
      ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

build: &build
  steps:
    - checkout
    - <<: *fake_ssh_keys
    - <<: *install_elixir
    - <<: *install_hex_rebar
    - <<: *install_nerves_bootstrap
    - run:
        name: Build Project
        command: |
          cd $MIX_PROJECT
          n=0
          until [ $n -ge 5 ]; do
            mix deps.get && break
            n=$((n+1))
            echo "Error while fetching deps. Retrying in 5 seconds"
            sleep 5
          done
          mix firmware

jobs:
  blinky_rpi0:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "blinky"
      MIX_TARGET: "rpi0"
    <<: *build

  blinky_rpi:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "blinky"
      MIX_TARGET: "rpi"
    <<: *build

  blinky_rpi2:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "blinky"
      MIX_TARGET: "rpi2"
    <<: *build

  blinky_rpi3:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "blinky"
      MIX_TARGET: "rpi3"
    <<: *build

  blinky_rpi3a:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "blinky"
      MIX_TARGET: "rpi3a"
    <<: *build

  blinky_rpi4:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "blinky"
      MIX_TARGET: "rpi4"
    <<: *build

  blinky_bbb:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "blinky"
      MIX_TARGET: "bbb"
    <<: *build

  hello_gpio_rpi0:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_gpio"
      MIX_TARGET: "rpi0"
    <<: *build

  hello_gpio_rpi:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_gpio"
      MIX_TARGET: "rpi"
    <<: *build

  hello_gpio_rpi2:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_gpio"
      MIX_TARGET: "rpi2"
    <<: *build

  hello_gpio_rpi3:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_gpio"
      MIX_TARGET: "rpi3"
    <<: *build

  hello_gpio_rpi3a:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_gpio"
      MIX_TARGET: "rpi3a"
    <<: *build

  hello_gpio_rpi4:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_gpio"
      MIX_TARGET: "rpi4"
    <<: *build

  hello_gpio_bbb:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_gpio"
      MIX_TARGET: "bbb"
    <<: *build

  hello_leds_rpi0:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_leds"
      MIX_TARGET: "rpi0"
    <<: *build

  hello_leds_rpi:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_leds"
      MIX_TARGET: "rpi"
    <<: *build

  hello_leds_rpi2:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_leds"
      MIX_TARGET: "rpi2"
    <<: *build

  hello_leds_rpi3:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_leds"
      MIX_TARGET: "rpi3"
    <<: *build

  hello_leds_rpi3a:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_leds"
      MIX_TARGET: "rpi3a"
    <<: *build

  hello_leds_rpi4:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_leds"
      MIX_TARGET: "rpi4"
    <<: *build

  hello_leds_bbb:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_leds"
      MIX_TARGET: "bbb"
    <<: *build

  hello_network_rpi0:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_network"
      MIX_TARGET: "rpi0"
    <<: *build

  hello_network_rpi:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_network"
      MIX_TARGET: "rpi"
    <<: *build

  hello_network_rpi2:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_network"
      MIX_TARGET: "rpi2"
    <<: *build

  hello_network_rpi3:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_network"
      MIX_TARGET: "rpi3"
    <<: *build

  hello_network_rpi3a:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_network"
      MIX_TARGET: "rpi3a"
    <<: *build

  hello_network_rpi4:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_network"
      MIX_TARGET: "rpi4"
    <<: *build

  hello_network_bbb:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_network"
      MIX_TARGET: "bbb"
    <<: *build

  hello_network_x86_64:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_network"
      MIX_TARGET: "x86_64"
    <<: *build

  hello_phoenix_rpi0:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_phoenix/firmware"
      MIX_TARGET: "rpi0"
    <<: *build

  hello_phoenix_rpi:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_phoenix/firmware"
      MIX_TARGET: "rpi"
    <<: *build

  hello_phoenix_rpi2:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_phoenix/firmware"
      MIX_TARGET: "rpi2"
    <<: *build

  hello_phoenix_rpi3:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_phoenix/firmware"
      MIX_TARGET: "rpi3"
    <<: *build

  hello_phoenix_rpi3a:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_phoenix/firmware"
      MIX_TARGET: "rpi3a"
    <<: *build

  hello_phoenix_rpi4:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_phoenix/firmware"
      MIX_TARGET: "rpi4"
    <<: *build

  hello_phoenix_bbb:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_phoenix/firmware"
      MIX_TARGET: "bbb"
    <<: *build

  hello_phoenix_x86_64:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_phoenix/firmware"
      MIX_TARGET: "x86_64"
    <<: *build

  hello_lfe_rpi0:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_lfe"
      MIX_TARGET: "rpi0"
    <<: *build

  hello_lfe_rpi:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_lfe"
      MIX_TARGET: "rpi"
    <<: *build

  hello_lfe_rpi2:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_lfe"
      MIX_TARGET: "rpi2"
    <<: *build

  hello_lfe_rpi3:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_lfe"
      MIX_TARGET: "rpi3"
    <<: *build

  hello_lfe_rpi3a:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_lfe"
      MIX_TARGET: "rpi3a"
    <<: *build

  hello_lfe_rpi4:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_lfe"
      MIX_TARGET: "rpi4"
    <<: *build

  hello_lfe_bbb:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_lfe"
      MIX_TARGET: "bbb"
    <<: *build

  hello_lfe_x86_64:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_lfe"
      MIX_TARGET: "x86_64"
    <<: *build

  hello_erlang_rpi0:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_erlang"
      MIX_TARGET: "rpi0"
    <<: *build

  hello_erlang_rpi:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_erlang"
      MIX_TARGET: "rpi"
    <<: *build

  hello_erlang_rpi2:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_erlang"
      MIX_TARGET: "rpi2"
    <<: *build

  hello_erlang_rpi3:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_erlang"
      MIX_TARGET: "rpi3"
    <<: *build

  hello_erlang_rpi3a:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_erlang"
      MIX_TARGET: "rpi3a"
    <<: *build

  hello_erlang_rpi4:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_erlang"
      MIX_TARGET: "rpi4"
    <<: *build

  hello_erlang_bbb:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_erlang"
      MIX_TARGET: "bbb"
    <<: *build

  hello_erlang_x86_64:
    <<: *defaults
    environment:
      <<: *elixir_version
      MIX_PROJECT: "hello_erlang"
      MIX_TARGET: "x86_64"
    <<: *build

workflows:
  version: 2
  build:
    jobs:
      - blinky_rpi0:
          context: org-global
      - blinky_rpi:
          context: org-global
      - blinky_rpi2:
          context: org-global
      - blinky_rpi3:
          context: org-global
      - blinky_rpi3a:
          context: org-global
      - blinky_rpi4:
          context: org-global
      - blinky_bbb:
          context: org-global
      - hello_gpio_rpi0:
          context: org-global
      - hello_gpio_rpi:
          context: org-global
      - hello_gpio_rpi2:
          context: org-global
      - hello_gpio_rpi3:
          context: org-global
      - hello_gpio_rpi3a:
          context: org-global
      - hello_gpio_rpi4:
          context: org-global
      - hello_gpio_bbb:
          context: org-global
      - hello_leds_rpi0:
          context: org-global
      - hello_leds_rpi:
          context: org-global
      - hello_leds_rpi2:
          context: org-global
      - hello_leds_rpi3:
          context: org-global
      - hello_leds_rpi3a:
          context: org-global
      - hello_leds_rpi4:
          context: org-global
      - hello_leds_bbb:
          context: org-global
      - hello_network_rpi0:
          context: org-global
      - hello_network_rpi:
          context: org-global
      - hello_network_rpi2:
          context: org-global
      - hello_network_rpi3:
          context: org-global
      - hello_network_rpi3a:
          context: org-global
      - hello_network_rpi4:
          context: org-global
      - hello_network_bbb:
          context: org-global
      - hello_network_x86_64:
          context: org-global
      - hello_phoenix_rpi0:
          context: org-global
      - hello_phoenix_rpi:
          context: org-global
      - hello_phoenix_rpi2:
          context: org-global
      - hello_phoenix_rpi3:
          context: org-global
      - hello_phoenix_rpi3a:
          context: org-global
      - hello_phoenix_rpi4:
          context: org-global
      - hello_phoenix_bbb:
          context: org-global
      - hello_phoenix_x86_64:
          context: org-global
      - hello_lfe_rpi0:
          context: org-global
      - hello_lfe_rpi:
          context: org-global
      - hello_lfe_rpi2:
          context: org-global
      - hello_lfe_rpi3:
          context: org-global
      - hello_lfe_rpi3a:
          context: org-global
      - hello_lfe_rpi4:
          context: org-global
      - hello_lfe_bbb:
          context: org-global
      - hello_lfe_x86_64:
          context: org-global
      - hello_erlang_rpi0:
          context: org-global
      - hello_erlang_rpi:
          context: org-global
      - hello_erlang_rpi2:
          context: org-global
      - hello_erlang_rpi3:
          context: org-global
      - hello_erlang_rpi3a:
          context: org-global
      - hello_erlang_rpi4:
          context: org-global
      - hello_erlang_bbb:
          context: org-global
      - hello_erlang_x86_64:
          context: org-global
